### ISSUE TITLE
Register in Elixir **LocTree 2** (not 3) (since 3 is already there)

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/LocTree#4]

**Comment by amerello** [comment]
https://bio.tools/tool/tum.de/LocTree2/1

**Comment by juanmirocks** [comment]
wait, what? Did you do it already ? :P 

How did you log in ?

**Comment by amerello** [comment]
yes, I created an account on the website and added the entry for loctree2

**Comment by juanmirocks** [comment]
Nice. Awesome job.
