### ISSUE TITLE
Put Dockerfile image onto Docker hub (Rostlab organization)

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/LocTree#6]

**Comment by amerello** [comment]
I don't have the login credentials for the Rostlab organization, so I pushed the Docker image to the following hub: https://hub.docker.com/r/amerello/loctree3/ It is based on the same Docker recipe from README.md. It was pushed with the following steps:

```
docker login
docker build -t amerello/loctree3 .
docker push amerello/loctree3
```

**Comment by juanmirocks** [comment]
That's great Alejandro -- I added you as a member of the students team on Docker.

Can you try now?

**Comment by amerello** [comment]
Thanks! as a member from the student team I still cannot create a repository under the Rostlab namespace, namely rostlab/loctree3. Could it be that I don't have this priviledge?

**Comment by juanmirocks** [comment]
I created the repo and gave you write rights: https://hub.docker.com/r/rostlab/loctree3/

Check now :)

**Comment by amerello** [comment]
Thanks! now I was able to push to rostlab/loctree3. The image is now available there.

**Comment by juanmirocks** [comment]
:tada:

**Comment by juanmirocks** [comment]
Thank you so much. You guys did a great job.
